### ISSUE TITLE
Gray-Scott: Build error, possible API change

### ISSUE THREAD

**Issue by j-woz** [pnorbert/adiosvm#23]
I am getting the following error using git master in ADIOS2 and adiosvm - do I need to use some other versions?

$ adiosvm/Tutorial/gray-scott/build> make
[ 16%] Building CXX object CMakeFiles/gray-scott.dir/simulation/main.cpp.o
/home/wozniak/proj/adiosvm/Tutorial/gray-scott/simulation/main.cpp: In function ‘int main
(int, char**)’:
/home/wozniak/proj/adiosvm/Tutorial/gray-scott/simulation/main.cpp:74:69: error: no match
ing function for call to ‘adios2::ADIOS::ADIOS(std::__cxx11::string&, ompi_communicator_t
*&, const bool&)’
     adios2::ADIOS adios(settings.adios_config, comm, adios2::DebugON);
                                                                     ^
In file included from /home/wozniak/Public/sfw/ADIOS2/include/adios2.h:18:0,
                 from /home/wozniak/proj/adiosvm/Tutorial/gray-scott/simulation/main.cpp:5:
/home/wozniak/Public/sfw/ADIOS2/include/cxx11/ADIOS.h:104:5: note: candidate: adios2::ADIOS::ADIOS(adios2::ADIOS&&)
     ADIOS(ADIOS &&) = default;
     ^~~~~
/home/wozniak/Public/sfw/ADIOS2/include/cxx11/ADIOS.h:104:5: note:   candidate expects 1 argument, 3 provided

**Comment by williamfgc** [comment]
@jmjwozniak you need an MPI version of adios2. The error says this ADIOS2 version was compiled without MPI.

**Comment by j-woz** [comment]
That was it, thanks!
