### ISSUE TITLE
Gray-scott cannot work with SST engine in Bebop

### ISSUE THREAD

**Issue by tongshu83** [pnorbert/adiosvm#29]
1. load modules
module unload intel-mkl/2017.3.196-v7uuj6z
module load intel/17.0.4-74uvhji
module load intel-mpi/2017.3-dfphq6k
module load libpsm2/10.3-17
module load cmake/3.12.2-4zllpyo
module load jdk/8u141-b15-mopj6qr
module load tcl/8.6.6-x4wnbsg
module load bzip2/1.0.6-hcvyuh5
module load zlib/1.2.11-6632jqd

2. install ADIOS2
export ROOT=$PWD/install
git clone https://github.com/ornladios/ADIOS2.git
cd ADIOS2
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=$ROOT/adios2 ..
make -j8
make install
cd ../..
export PATH=$ROOT/adios2/bin:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ROOT/adios2/lib64

3. Build the application
git clone https://github.com/pnorbert/adiosvm.git
cd adiosvm/Tutorial/gray-scott
mkdir build && cd build
cmake -DADIOS2_DIR=$ROOT/adios2 ..
make -j8
cd ..

4. Run the application
Set the engine type of simulation as SST

$ mpirun -n 4 build/gray-scott simulation/settings.json
Simulation writes data using engine type:              SST
#========================================
grid:             48x48x48
steps:            600
plotgap:          25
F:                0.02
k:                0.048
dt:               1
Du:               0.2
Dv:               0.1
noise:            0.01
output:           gs.bp
adios_config:     adios2.xml
decomposition:    2x2x1
grid per process: 24x24x48
#========================================
Simulation at step 0 writing output step     0
terminate called after throwing an instance of 'std::invalid_argument'
terminate called after throwing an instance of 'std::invalid_argument'
terminate called after throwing an instance of 'std::invalid_argument'
terminate called after throwing an instance of 'std::invalid_argument'
  what():  ERROR: Engine derived class SstWriter doesn't implement function DoPut
  what():  ERROR: Engine derived class SstWriter doesn't implement function DoPut

  what():  ERROR: Engine derived class SstWriter doesn't implement function DoPut

gray-scott:120537 terminated with signal 6 at PC=2b2622ee1207 SP=7ffc5b80e1d8.  Backtrace:
  what():  ERROR: Engine derived class SstWriter doesn't implement function DoPut

gray-scott:120538 terminated with signal 6 at PC=2abb680cb207 SP=7ffcd35bce68.  Backtrace:

gray-scott:120539 terminated with signal 6 at PC=2ac17f721207 SP=7ffc878d2bd8.  Backtrace:

gray-scott:120536 terminated with signal 6 at PC=2b027ce3a207 SP=7ffc5c54fcf8.  Backtrace:
/lib64/libc.so.6(gsignal+0x37)[0x2b027ce3a207]
/lib64/libc.so.6(abort+0x148)[0x2b027ce3b8f8]
/lib64/libc.so.6(gsignal+0x37)[0x2b2622ee1207]
/lib64/libc.so.6(abort+0x148)[0x2b2622ee28f8]
/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x165)[0x2b26226ec7d5]
/lib64/libc.so.6(gsignal+0x37)[0x2abb680cb207]
/lib64/libc.so.6(abort+0x148)[0x2abb680cc8f8]
/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x165)[0x2abb678d67d5]
/lib64/libc.so.6(gsignal+0x37)[0x2ac17f721207]
/lib64/libc.so.6(abort+0x148)[0x2ac17f7228f8]
/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x165)[0x2ac17ef2c7d5]
/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x165)[0x2b027c6457d5]
/lib64/libstdc++.so.6(+0x5e746)[0x2b027c643746]
/lib64/libstdc++.so.6(+0x5e746)[0x2b26226ea746]
/lib64/libstdc++.so.6(+0x5e746)[0x2abb678d4746]
/lib64/libstdc++.so.6(+0x5e746)[0x2ac17ef2a746]
/lib64/libstdc++.so.6(+0x5e773)[0x2b26226ea773]
/lib64/libstdc++.so.6(+0x5e773)[0x2abb678d4773]
/lib64/libstdc++.so.6(+0x5e773)[0x2ac17ef2a773]
/lib64/libstdc++.so.6(+0x5e773)[0x2b027c643773]
/lib64/libstdc++.so.6(+0x5e993)[0x2b027c643993]
/lib64/libstdc++.so.6(+0x5e993)[0x2b26226ea993]
/lib64/libstdc++.so.6(+0x5e993)[0x2abb678d4993]
/lib64/libstdc++.so.6(+0x5e993)[0x2ac17ef2a993]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZNK6adios24core6Engine7ThrowUpESs+0x102)[0x2b027a8bada2]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZNK6adios24core6Engine7ThrowUpESs+0x102)[0x2b2620961da2]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZNK6adios24core6Engine7ThrowUpESs+0x102)[0x2abb65b4bda2]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZNK6adios24core6Engine7ThrowUpESs+0x102)[0x2ac17d1a1da2]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZN6adios24core6Engine5DoPutERNS0_8VariableIdEERNS0_4SpanIdEEmRKd+0x2d)[0x2b027a8bb89d]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZN6adios24core6Engine5DoPutERNS0_8VariableIdEERNS0_4SpanIdEEmRKd+0x2d)[0x2b262096289d]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZN6adios24core6Engine5DoPutERNS0_8VariableIdEERNS0_4SpanIdEEmRKd+0x2d)[0x2abb65b4c89d]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZN6adios24core6Engine5DoPutERNS0_8VariableIdEERNS0_4SpanIdEEmRKd+0x2d)[0x2ac17d1a289d]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZN6adios24core6Engine3PutIdEERNS0_8VariableIT_E4SpanERS5_mRKS4_+0x135)[0x2b027a8d2d05]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZN6adios24core6Engine3PutIdEERNS0_8VariableIT_E4SpanERS5_mRKS4_+0x135)[0x2b2620979d05]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZN6adios24core6Engine3PutIdEERNS0_8VariableIT_E4SpanERS5_mRKS4_+0x135)[0x2abb65b63d05]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZN6adios24core6Engine3PutIdEERNS0_8VariableIT_E4SpanERS5_mRKS4_+0x135)[0x2ac17d1b9d05]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZN6adios26Engine3PutIdEENS_8VariableIT_E4SpanES4_mRKS3_+0xb9)[0x2abb65e22929]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZN6adios26Engine3PutIdEENS_8VariableIT_E4SpanES4_mRKS3_+0xb9)[0x2ac17d478929]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZN6adios26Engine3PutIdEENS_8VariableIT_E4SpanES4_mRKS3_+0xb9)[0x2b027ab91929]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZN6adios26Engine3PutIdEENS_8VariableIT_E4SpanES4_mRKS3_+0xb9)[0x2b2620c38929]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZN6adios26Engine3PutIdEENS_8VariableIT_E4SpanES4_+0x1a)[0x2abb65e229ba]
build/gray-scott[0x405d45]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZN6adios26Engine3PutIdEENS_8VariableIT_E4SpanES4_+0x1a)[0x2ac17d4789ba]
build/gray-scott[0x405d45]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZN6adios26Engine3PutIdEENS_8VariableIT_E4SpanES4_+0x1a)[0x2b027ab919ba]
build/gray-scott[0x405d45]
/home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2(_ZN6adios26Engine3PutIdEENS_8VariableIT_E4SpanES4_+0x1a)[0x2b2620c389ba]
build/gray-scott[0x405d45]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x2abb680b73d5]
build/gray-scott[0x4041a9]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x2ac17f70d3d5]
build/gray-scott[0x4041a9]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x2b027ce263d5]
build/gray-scott[0x4041a9]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x2b2622ecd3d5]
build/gray-scott[0x4041a9]

gray-scott:120539 terminated with signal 11 at PC=2ac1864e75bf SP=2ac18a319e20.  Backtrace:
SST stream open at exit, unlinking contact file /blues/gpfs/home/tshu/project/bebop/HPC_Autotuner/adiosvm/Tutorial/gray-scott/gs.bp.sst

$ ldd gray-scott 
	linux-vdso.so.1 =>  (0x00007ffde95aa000)
	libadios2.so.2 => /home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2.so.2 (0x00002af278e06000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002af279584000)
	libmpifort.so.12 => /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/intel-mpi-2017.3-dfphq6kavje2olnichisvjjndtridrok/compilers_and_libraries_2017.4.196/linux/mpi/intel64/lib/libmpifort.so.12 (0x00002af2797a0000)
	libmpi.so.12 => /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/intel-mpi-2017.3-dfphq6kavje2olnichisvjjndtridrok/compilers_and_libraries_2017.4.196/linux/mpi/intel64/lib/libmpi.so.12 (0x00002af279b49000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002af27a871000)
	librt.so.1 => /lib64/librt.so.1 (0x00002af27aa75000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00002af27ac7d000)
	libm.so.6 => /lib64/libm.so.6 (0x00002af27af84000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00002af27b286000)
	libc.so.6 => /lib64/libc.so.6 (0x00002af27b49c000)
	libadios2_sst.so.2 => /home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2_sst.so.2 (0x00002af27b869000)
	libbz2.so.1.0 => /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/bzip2-1.0.6-hcvyuh5a7fzugpdvauilafgcvhqc2ajb/lib/libbz2.so.1.0 (0x00002af27ba88000)
	libtaustubs.so => /home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libtaustubs.so (0x00002af27bcd8000)
	/lib64/ld-linux-x86-64.so.2 (0x00002af278be2000)
	libfabric.so.1 => /lib64/libfabric.so.1 (0x00002af27bedc000)
	libadios2_evpath.so => /home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2_evpath.so (0x00002af27c233000)
	libadios2_ffs.so.1 => /home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2_ffs.so.1 (0x00002af27c4a7000)
	libadios2_atl.so.2 => /home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/libadios2_atl.so.2 (0x00002af27c70d000)
	libimf.so => /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-17.0.4-74uvhjiulyqgvsmywifbbuo46v5n42xc/compilers_and_libraries_2017.4.193/linux/compiler/lib/intel64_lin/libimf.so (0x00002af27c91b000)
	libsvml.so => /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-17.0.4-74uvhjiulyqgvsmywifbbuo46v5n42xc/compilers_and_libraries_2017.4.193/linux/compiler/lib/intel64_lin/libsvml.so (0x00002af27ce08000)
	libirng.so => /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-17.0.4-74uvhjiulyqgvsmywifbbuo46v5n42xc/compilers_and_libraries_2017.4.193/linux/compiler/lib/intel64_lin/libirng.so (0x00002af27dd21000)
	libintlc.so.5 => /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-17.0.4-74uvhjiulyqgvsmywifbbuo46v5n42xc/compilers_and_libraries_2017.4.193/linux/compiler/lib/intel64_lin/libintlc.so.5 (0x00002af27e096000)
	librdmacm.so.1 => /lib64/librdmacm.so.1 (0x00002af27e301000)
	libibverbs.so.1 => /lib64/libibverbs.so.1 (0x00002af27e518000)
	libnl-route-3.so.200 => /lib64/libnl-route-3.so.200 (0x00002af27e72f000)
	libpsm_infinipath.so.1 => /lib64/libpsm_infinipath.so.1 (0x00002af27e99c000)
	libnl-3.so.200 => /lib64/libnl-3.so.200 (0x00002af27ebf2000)
	libpsm2.so.2 => /soft/bebop/libpsm2/10.3-17/usr/lib64/libpsm2.so.2 (0x00002af27ee13000)
	libadios2_dill.so.2 => /home/tshu/project/bebop/HPC_Autotuner/install/adios2/lib64/../lib64/libadios2_dill.so.2 (0x00002af27f072000)
	libinfinipath.so.4 => /lib64/libinfinipath.so.4 (0x00002af27f2a7000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00002af27f4b6000)
	libnuma.so.1 => /lib64/libnuma.so.1 (0x00002af27f6bb000)

**Comment by pnorbert** [comment]
I turned off using span mode in the simulations/setting.json. Now it should work from master.

**Comment by keichi** [comment]
@tongshu83 Please close this issue if your problem has been resolved.
