### ISSUE TITLE
Failure on compiling the gray-scott

### ISSUE THREAD

**Issue by tongshu83** [pnorbert/adiosvm#32]
Compiling the gray-scott...
$ make
Scanning dependencies of target gray-scott
Scanning dependencies of target pdf_calc
[ 16%] Building CXX object CMakeFiles/pdf_calc.dir/analysis/pdf_calc.cpp.o
[ 33%] Building CXX object CMakeFiles/gray-scott.dir/simulation/gray-scott.cpp.o
[ 50%] Building CXX object CMakeFiles/gray-scott.dir/simulation/main.cpp.o
[ 66%] Building CXX object CMakeFiles/gray-scott.dir/simulation/settings.cpp.o
/home/tshu/project/MPI_in_MPI/t7810/adiosvm/Tutorial/gray-scott/analysis/pdf_calc.cpp: In function ‘int main(int, char**)’:
/home/tshu/project/MPI_in_MPI/t7810/adiosvm/Tutorial/gray-scott/analysis/pdf_calc.cpp:212:59: error: ‘NextAvailable’ is not a member of ‘adios2::StepMode’
         adios2::StepStatus read_status = reader.BeginStep(adios2::StepMode::NextAvailable, 10.0f);
                                                           ^
CMakeFiles/pdf_calc.dir/build.make:62: recipe for target 'CMakeFiles/pdf_calc.dir/analysis/pdf_calc.cpp.o' failed
make[2]: *** [CMakeFiles/pdf_calc.dir/analysis/pdf_calc.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/pdf_calc.dir/all' failed
make[1]: *** [CMakeFiles/pdf_calc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 83%] Linking CXX executable gray-scott
[ 83%] Built target gray-scott
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pnorbert** [comment]
There was a change in ADIOS2 master but the corresponding PR here was not merged. It is now. Please update  your adiosvm.

**Comment by keichi** [comment]
@tongshu83 Can you please close this issue if your problem has been resolved.
